

---- INSTRUMENTS inserts
INSERT INTO INSTRUMENTS (INSTRUMENT_ID, CREATED_BY, CREATED_ON, INSTRUMENT_NAME) VALUES (1001, 'sachin', sysdate, 'Instrument-1');
INSERT INTO INSTRUMENTS (INSTRUMENT_ID, CREATED_BY, CREATED_ON, INSTRUMENT_NAME) VALUES (1002, 'sachin', sysdate, 'Instrument-2');
INSERT INTO INSTRUMENTS (INSTRUMENT_ID, CREATED_BY, CREATED_ON, INSTRUMENT_NAME) VALUES (1003, 'sachin', sysdate, 'Instrument-3');

---- inserts ORDER_BOOK_STATUS
INSERT INTO ORDER_BOOK_STATUS (ORDER_BOOK_STATUS_ID, CREATED_BY, CREATED_ON, STATUS_VALUE) VALUES (1001, 'sachin', sysdate, 'Open');
INSERT INTO ORDER_BOOK_STATUS (ORDER_BOOK_STATUS_ID, CREATED_BY, CREATED_ON, STATUS_VALUE) VALUES (1002, 'sachin', sysdate, 'Closed');

---- inserts ORDER_STATUS
INSERT INTO ORDER_STATUS (ORDER_STATUS_ID, CREATED_BY, CREATED_ON, STATUS_VALUE) VALUES (1001, 'sachin', sysdate, 'Valid');
INSERT INTO ORDER_STATUS (ORDER_STATUS_ID, CREATED_BY, CREATED_ON, STATUS_VALUE) VALUES (1002, 'sachin', sysdate, 'InValid');

---- inserts ORDER_TYPE
INSERT INTO ORDER_TYPE (ORDER_TYPE_ID, CREATED_BY, CREATED_ON, ORDER_TYPE, LIMIT_VALUE) VALUES (1001, 'sachin', sysdate, 'Limit Order', '50');
INSERT INTO ORDER_TYPE (ORDER_TYPE_ID, CREATED_BY, CREATED_ON, ORDER_TYPE) VALUES (1002, 'sachin', sysdate, 'Market Order');


---- inserts ORDER_BOOK_INV
INSERT INTO ORDER_BOOK_INV (ORDER_BOOK_ID, CREATED_BY, CREATED_ON, ORDER_BOOK_NAME, INSTRUMENT_ID, ORDER_BOOK_STATUS_ID) 
VALUES (1001, 'sachin', sysdate, 'Book-1', 1001, 1001);
INSERT INTO ORDER_BOOK_INV (ORDER_BOOK_ID, CREATED_BY, CREATED_ON, ORDER_BOOK_NAME, INSTRUMENT_ID, ORDER_BOOK_STATUS_ID) 
VALUES (1002, 'sachin', sysdate, 'Book-2', 1002, 1001);


---- inserts ORDERS_INV
INSERT INTO ORDERS_INV (ORDER_ID, CREATED_BY, CREATED_ON, ORDER_NAME, ORDER_QUANTITY, ORDER_PRICE, INSTRUMENT_ID, ORDER_STATUS_ID, ORDER_TYPE_ID,ORDER_BOOK_ID) 
VALUES (1001, 'sachin', sysdate, 'Order-1', 200, 200, 1001, 1001, 1001,1001);
INSERT INTO ORDERS_INV (ORDER_ID, CREATED_BY, CREATED_ON, ORDER_NAME, ORDER_QUANTITY, ORDER_PRICE, INSTRUMENT_ID, ORDER_STATUS_ID, ORDER_TYPE_ID) 
VALUES (1002, 'sachin', sysdate, 'Order-1', 3, 505, 1001, 1001, 1001);

---- execution inserts 
INSERT INTO EXECUTION(EXECUTION_ID, CREATED_BY, EXECUTION_NAME, PRICE,order_book_id,qty) VALUES (1001, 'sachin', 'Execution-1', 502,1001,100);
INSERT INTO EXECUTION(EXECUTION_ID, CREATED_BY, EXECUTION_NAME, PRICE,order_book_id,qty) VALUES (1002, 'sachin', 'Execution-2', 502,1002,200);

 
insert into role VALUES (1001, 'ADMIN');



